name: remote ssh command
on: 
    push:
        branches:
          - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /home/shopify-apps/reports/advance-reports-api/
            git stash
            git pull
            npm install
            pm2 restart 9
